#!/usr/bin/env bash
set -euo pipefail
export PATH=$PATH:/usr/local/bin

# Function to send webhook
send_webhook() {
  local type=$1
  local status=$2
  local error_msg=${3:-""}
  local pr_url=${4:-""}
  local message=${5:-""}
  
  if [ -z "$WEBHOOK_URL" ]; then
    echo "[pj] Warning: WEBHOOK_URL not set, skipping webhook"
    return
  fi
  
  local payload=$(cat <<EOF
{
  "type": "$type",
  "taskId": "$TASK_ID",
  "workspaceId": "${WORKSPACE_ID:-unknown}",
  "branchName": "${BRANCH_NAME:-}",
  "prUrl": "$pr_url",
  "status": "$status",
  "error": "$error_msg",
  "message": "$message"
}
EOF
)
  
  echo "[pj] Sending webhook: $type"
  curl -X POST "$WEBHOOK_URL" \
    -H "Content-Type: application/json" \
    -d "$payload" \
    --max-time 10 \
    --silent \
    --show-error || echo "[pj] Warning: Webhook delivery failed"
}

# Function to handle errors
handle_error() {
  local error_msg=$1
  echo "[pj] Error: $error_msg" >&2
  send_webhook "task.failed" "failed" "$error_msg"
  exit 1
}

# Trap errors
trap 'handle_error "Script failed at line $LINENO"' ERR

echo "[pj] ========================================"
echo "[pj] Starting execution for task: $TASK_ID"
echo "[pj] ========================================"
echo "[pj] Target repo: $TARGET_REPO"
echo "[pj] Branch name: ${BRANCH_NAME:-pj/${TASK_ID}}"
echo "[pj] Model provider: ${MODEL_PROVIDER:-openai}"
echo "[pj] Model: ${MODEL:-gpt-4o}"

# Validate required environment variables
if [ -z "$TARGET_REPO" ]; then
  handle_error "TARGET_REPO environment variable is required"
fi

if [ -z "$TASK_ID" ]; then
  handle_error "TASK_ID environment variable is required"
fi

if [ -z "$AGENT_PROMPT" ]; then
  handle_error "AGENT_PROMPT environment variable is required"
fi

# Configure git
git config --global user.name "Pithy Jaunt Bot"
git config --global user.email "bot@pithy-jaunt.dev"

# Validate GitHub token if provided (needed for PR creation)
if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "[pj] Warning: GITHUB_TOKEN not set, PR creation will fail"
fi

# Create working directory
mkdir -p /tmp/pj
cd /tmp/pj

# Clone repository
echo "[pj] Cloning repository: $TARGET_REPO"
send_webhook "task.progress" "running" "" "" "Cloning repository..." || true  # Send progress update (non-blocking)
if ! git clone "$TARGET_REPO" repo; then
  handle_error "Failed to clone repository: $TARGET_REPO"
fi

cd repo

# Determine base branch (default to main)
BASE_BRANCH=${BASE_BRANCH:-main}
if ! git show-ref --verify --quiet refs/heads/"$BASE_BRANCH"; then
  # Try master if main doesn't exist
  if git show-ref --verify --quiet refs/heads/master; then
    BASE_BRANCH=master
  else
    # Use the default branch
    BASE_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
  fi
fi

echo "[pj] Base branch: $BASE_BRANCH"
git checkout "$BASE_BRANCH"

# Create branch
BRANCH=${BRANCH_NAME:-pj/${TASK_ID}}
echo "[pj] Creating branch: $BRANCH"
if ! git checkout -b "$BRANCH"; then
  # Branch might already exist, try to delete and recreate
  git branch -D "$BRANCH" 2>/dev/null || true
  git checkout -b "$BRANCH"
fi

# Add CodeRabbit configuration if missing
if [ ! -f .coderabbit.yaml ]; then
  echo "[pj] Adding CodeRabbit configuration..."
  
  cat > .coderabbit.yaml << 'EOF'
# CodeRabbit Configuration
# Generated by Pithy Jaunt

review:
  enabled: true
  review_all_files: true
  focus:
    - code_quality
    - security
    - performance
    - maintainability
    - best_practices

analysis:
  enabled: true
  summaries:
    enabled: true
    format: markdown
  tasks:
    enabled: true
    min_priority: medium

output:
  format: markdown
  include_suggestions: true
  include_code_examples: true
EOF

  git add .coderabbit.yaml
  git commit -m "Add CodeRabbit configuration (Pithy Jaunt)" || true
  
  echo "[pj] CodeRabbit configuration added"
fi

# Run AI agent to generate patch
echo "[pj] Running AI agent to generate code changes..."
echo "[pj] Task description: $AGENT_PROMPT"
send_webhook "task.progress" "running" "" "" "Running AI agent to generate code changes..." || true  # Send progress update (non-blocking)

if ! python3 /app/agent-runner.py \
  --prompt-file /app/system-prompt.md \
  --task "$AGENT_PROMPT" \
  --repo-path "$(pwd)" \
  --out /tmp/patch.diff \
  --provider "${MODEL_PROVIDER:-openai}" \
  --model "${MODEL:-gpt-4o}"; then
  handle_error "AI agent failed to generate patch"
fi

# Check if patch file exists and is not empty
if [ ! -f /tmp/patch.diff ] || [ ! -s /tmp/patch.diff ]; then
  handle_error "Patch file is empty or missing"
fi

echo "[pj] Patch generated successfully"
echo "[pj] Patch size: $(wc -l < /tmp/patch.diff) lines"

# Apply patch
echo "[pj] Applying patch..."
if ! git apply /tmp/patch.diff; then
  handle_error "Failed to apply patch. The patch may be invalid or conflict with existing code."
fi

echo "[pj] Patch applied successfully"

# Commit changes
git add -A
if ! git diff --cached --quiet; then
  git commit -m "Pithy Jaunt: $TASK_ID" || handle_error "Failed to commit changes"
  echo "[pj] Changes committed"
else
  echo "[pj] No changes to commit"
fi

# Push branch
echo "[pj] Pushing branch to remote..."
if ! git push origin "$BRANCH"; then
  handle_error "Failed to push branch to remote"
fi

echo "[pj] Branch pushed successfully"

# Create PR using GitHub REST API
echo "[pj] Creating pull request..."

# Parse repository URL to extract owner and repo
# Supports both https://github.com/owner/repo.git and git@github.com:owner/repo.git
REPO_URL="$TARGET_REPO"
if [[ "$REPO_URL" =~ github\.com[:/]([^/]+)/([^/]+?)(\.git)?$ ]]; then
  REPO_OWNER="${BASH_REMATCH[1]}"
  REPO_NAME="${BASH_REMATCH[2]}"
  # Remove .git suffix if present
  REPO_NAME="${REPO_NAME%.git}"
  echo "[pj] Repository: $REPO_OWNER/$REPO_NAME"
else
  handle_error "Failed to parse repository URL: $REPO_URL"
fi

# Validate GitHub token
if [ -z "${GITHUB_TOKEN:-}" ]; then
  handle_error "GITHUB_TOKEN is required to create pull request"
fi

PR_BODY="Automated change for task $TASK_ID

**Task Description:**
$AGENT_PROMPT

**Generated by:** Pithy Jaunt AI Agent
**Model:** ${MODEL_PROVIDER:-openai}/${MODEL:-gpt-4o}
"

# Create PR using GitHub REST API
PR_URL=""
PR_PAYLOAD=$(cat <<EOF
{
  "title": "Pithy Jaunt: $TASK_ID",
  "body": $(echo "$PR_BODY" | jq -Rs .),
  "head": "$BRANCH",
  "base": "$BASE_BRANCH"
}
EOF
)

# Temporarily disable exit on error to handle PR creation errors
set +e
PR_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
  "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls" \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Content-Type: application/json" \
  -d "$PR_PAYLOAD" 2>&1)
PR_HTTP_CODE=$(echo "$PR_RESPONSE" | tail -1)
PR_BODY_RESPONSE=$(echo "$PR_RESPONSE" | sed '$d')
set -e

if [ "$PR_HTTP_CODE" = "201" ]; then
  # PR created successfully
  PR_URL=$(echo "$PR_BODY_RESPONSE" | jq -r '.html_url // .url // ""')
  if [ -z "$PR_URL" ] || [ "$PR_URL" = "null" ]; then
    # Fallback: construct URL manually
    PR_URL="https://github.com/$REPO_OWNER/$REPO_NAME/pull/$(echo "$PR_BODY_RESPONSE" | jq -r '.number')"
  fi
  echo "[pj] Pull request created: $PR_URL"
elif [ "$PR_HTTP_CODE" = "422" ]; then
  # PR might already exist, try to find it
  echo "[pj] PR creation returned 422, checking if PR already exists..."
  set +e
  EXISTING_PR=$(curl -s -X GET \
    "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls?head=$REPO_OWNER:$BRANCH&state=all" \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" 2>&1)
  set -e
  
  EXISTING_PR_URL=$(echo "$EXISTING_PR" | jq -r '.[0].html_url // .[0].url // ""' 2>/dev/null || echo "")
  if [ -n "$EXISTING_PR_URL" ] && [ "$EXISTING_PR_URL" != "null" ]; then
    PR_URL="$EXISTING_PR_URL"
    echo "[pj] Pull request already exists: $PR_URL"
  else
    # Parse error message from response
    ERROR_MSG=$(echo "$PR_BODY_RESPONSE" | jq -r '.message // "Unknown error"' 2>/dev/null || echo "Failed to create PR (HTTP $PR_HTTP_CODE)")
    handle_error "Failed to create pull request: $ERROR_MSG"
  fi
else
  # Other error
  ERROR_MSG=$(echo "$PR_BODY_RESPONSE" | jq -r '.message // "Unknown error"' 2>/dev/null || echo "Failed to create PR (HTTP $PR_HTTP_CODE)")
  handle_error "Failed to create pull request: $ERROR_MSG"
fi

# Run Browser Use tests if config present (optional)
if [ -f .browseruse.yml ]; then
  echo "[pj] Running Browser Use tests..."
  if command -v browser-use &> /dev/null; then
    browser-use run --config .browseruse.yml --save-screenshots /tmp/screens || echo "[pj] Browser Use tests failed (non-critical)"
  else
    echo "[pj] Browser Use not installed, skipping tests"
  fi
fi

# Send success webhook
send_webhook "task.completed" "success" "" "$PR_URL"

echo "[pj] ========================================"
echo "[pj] Execution completed successfully!"
echo "[pj] PR URL: $PR_URL"
echo "[pj] ========================================"

# Optionally keep workspace alive for debugging
if [ "${KEEP_ALIVE:-false}" = "true" ]; then
  echo "[pj] Keeping workspace alive for interactive debugging (15 minutes)..."
  sleep 900
fi

echo "[pj] Execution complete"

