#!/usr/bin/env bash
set -euo pipefail
export PATH=$PATH:/usr/local/bin

echo "[pj] starting execution for $TASK_ID"
mkdir -p /tmp/pj
cd /tmp/pj

echo "cloning $TARGET_REPO"
git clone "$TARGET_REPO" repo
cd repo

# create branch
BRANCH=${BRANCH_NAME:-pj/${TASK_ID}}
git checkout -b "$BRANCH"

# Add CodeRabbit configuration if missing
# This enables CodeRabbit to automatically analyze the repository
if [ ! -f .coderabbit.yaml ]; then
  echo "[pj] Adding CodeRabbit configuration..."
  
  cat > .coderabbit.yaml << 'EOF'
# CodeRabbit Configuration
# Generated by Pithy Jaunt

review:
  enabled: true
  review_all_files: true
  focus:
    - code_quality
    - security
    - performance
    - maintainability
    - best_practices

analysis:
  enabled: true
  summaries:
    enabled: true
    format: markdown
  tasks:
    enabled: true
    min_priority: medium

output:
  format: markdown
  include_suggestions: true
  include_code_examples: true
EOF

  # Commit the config
  git add .coderabbit.yaml
  git commit -m "Add CodeRabbit configuration (Pithy Jaunt)"
  
  echo "[pj] CodeRabbit configuration added"
  echo "[pj] CodeRabbit will automatically start analyzing when this PR is created"
fi

# run language agent
python3 /app/runner.py --prompt-file /app/system-prompt.md --task "$AGENT_PROMPT" --out /tmp/patch.diff

# apply patch
if git apply /tmp/patch.diff; then
  git add -A
  git commit -m "Pithy Jaunt automated change: $TASK_ID"
  git push origin "$BRANCH"
  # create PR using gh CLI
  gh pr create --title "Pithy Jaunt: $TASK_ID" --body "Automated change for task $TASK_ID" --base main --head "$BRANCH"
  echo "PR created"
  
  # CodeRabbit will automatically review the PR and post comments
  # Our webhook will receive those comments and create tasks
else
  echo "Patch failed to apply" >&2
  exit 2
fi

# run Browser Use tests if browser-use config present
if [ -f .browseruse.yml ]; then
  echo "running Browser Use tests"
  browser-use run --config .browseruse.yml --save-screenshots /tmp/screens
  # attach screenshots to the PR (upload flow or use GitHub API to attach)
fi

# optionally keep workspace alive until user closes
if [ "${KEEP_ALIVE:-false}" = "true" ]; then
  echo "keeping workspace alive for interactive debugging"
  sleep 900
fi

echo "execution complete"

