/**
 * Daytona CodeRabbit Setup
 * 
 * Functions to add CodeRabbit configuration to repositories
 * when they're cloned in Daytona workspaces
 */

import { generateCodeRabbitConfig, needsCodeRabbitConfig } from "@/lib/coderabbit/config";

/**
 * Setup CodeRabbit in a Daytona workspace
 * 
 * This should be called when:
 * 1. Repository is cloned in Daytona workspace
 * 2. CodeRabbit config is not detected
 * 
 * Steps:
 * 1. Create .coderabbit.yaml file
 * 2. Commit to a new branch
 * 3. CodeRabbit will automatically start analyzing
 */
export async function setupCodeRabbitInWorkspace(params: {
  workspacePath: string;
  repoUrl: string;
  branch: string;
  coderabbitDetected: boolean;
}): Promise<{
  success: boolean;
  branchName?: string;
  error?: string;
}> {
  const { workspacePath, branch, coderabbitDetected } = params;

  // Check if CodeRabbit config is needed
  if (!needsCodeRabbitConfig(coderabbitDetected)) {
    return {
      success: true,
      branchName: branch,
    };
  }

  try {
    // This will be executed in the Daytona workspace
    // The actual implementation will be in the execution script
    
    // Generate config content
    const configContent = generateCodeRabbitConfig();
    
    // Return instructions for the execution script
    return {
      success: true,
      branchName: `pj/add-coderabbit-${Date.now()}`,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
}

/**
 * Script content to add CodeRabbit config in Daytona workspace
 * This will be included in the Daytona execution script
 */
export const CODERABBIT_SETUP_SCRIPT = `
# Add CodeRabbit configuration if missing
if [ ! -f .coderabbit.yaml ]; then
  echo "[pj] Adding CodeRabbit configuration..."
  
  cat > .coderabbit.yaml << 'EOF'
# CodeRabbit Configuration
# Generated by Pithy Jaunt

review:
  enabled: true
  review_all_files: true
  focus:
    - code_quality
    - security
    - performance
    - maintainability
    - best_practices

analysis:
  enabled: true
  summaries:
    enabled: true
    format: markdown
  tasks:
    enabled: true
    min_priority: medium

output:
  format: markdown
  include_suggestions: true
  include_code_examples: true
EOF

  # Create branch for CodeRabbit config
  BRANCH_NAME="pj/add-coderabbit-$(date +%s)"
  git checkout -b "$BRANCH_NAME"
  
  # Commit the config
  git add .coderabbit.yaml
  git commit -m "Add CodeRabbit configuration (Pithy Jaunt)"
  
  # Push to trigger CodeRabbit analysis
  git push origin "$BRANCH_NAME"
  
  echo "[pj] CodeRabbit configuration added and pushed to $BRANCH_NAME"
  echo "[pj] CodeRabbit will automatically start analyzing the repository"
fi
`;

