/**
 * CodeRabbit Configuration
 * 
 * Creates .coderabbit.yaml configuration file for repositories
 * This is added to repos when they're cloned in Daytona workspaces
 */

export const CODERABBIT_CONFIG = `# CodeRabbit Configuration
# Generated by Pithy Jaunt

# Review settings
review:
  # Enable automatic reviews
  enabled: true
  
  # Review all files, not just changed ones
  review_all_files: true
  
  # Focus areas
  focus:
    - code_quality
    - security
    - performance
    - maintainability
    - best_practices

# Analysis settings
analysis:
  # Enable code analysis
  enabled: true
  
  # Generate summaries
  summaries:
    enabled: true
    format: markdown
  
  # Task suggestions
  tasks:
    enabled: true
    min_priority: medium

# Output format
output:
  format: markdown
  include_suggestions: true
  include_code_examples: true
`;

/**
 * Generate CodeRabbit configuration file content
 */
export function generateCodeRabbitConfig(): string {
  return CODERABBIT_CONFIG;
}

/**
 * Check if a repository needs CodeRabbit configuration
 * This will be called when setting up Daytona workspace
 */
export function needsCodeRabbitConfig(coderabbitDetected: boolean): boolean {
  return !coderabbitDetected;
}

