#!/usr/bin/env bash
# Helper script to extract Supabase access token from browser
# This makes it easier to get the token for the test script

echo "=========================================="
echo "How to get your Supabase Access Token"
echo "=========================================="
echo ""
echo "Method 1: From Browser DevTools (Easiest)"
echo "------------------------------------------"
echo "1. Open your production app in the browser"
echo "2. Open DevTools (F12 or Cmd+Option+I)"
echo "3. Go to the 'Application' tab (Chrome) or 'Storage' tab (Firefox)"
echo "4. In the left sidebar, expand 'Local Storage' or 'Session Storage'"
echo "5. Click on your app's domain (e.g., pithy-jaunt.vercel.app)"
echo "6. Look for a key like 'sb-<project-id>-auth-token'"
echo "7. The value is a JSON object - look for 'access_token' field"
echo "8. Copy that token value"
echo ""
echo "Method 2: From Network Tab"
echo "------------------------------------------"
echo "1. Open DevTools → Network tab"
echo "2. Make a request (e.g., load repos page)"
echo "3. Find a request to /api/repo or similar"
echo "4. Look at Request Headers"
echo "5. If you see 'Authorization: Bearer ...', copy the token part"
echo "6. If you only see Cookie header, use Method 1 or 3"
echo ""
echo "Method 3: From Browser Console"
echo "------------------------------------------"
echo "1. Open DevTools → Console tab"
echo "2. Run this JavaScript:"
echo ""
echo "   // For Supabase client in browser"
echo "   const { data: { session } } = await window.supabase.auth.getSession()"
echo "   console.log('Access Token:', session?.access_token)"
echo ""
echo "Method 4: Decode from Cookie (Advanced)"
echo "------------------------------------------"
echo "The cookie contains base64-encoded JSON. You can decode it:"
echo ""
echo "1. Copy the cookie value (the part after 'sb-...-auth-token=')"
echo "2. Remove the 'base64-' prefix if present"
echo "3. Decode it: echo 'BASE64_VALUE' | base64 -d"
echo "4. Parse the JSON and extract 'access_token' field"
echo ""
echo "=========================================="
echo "Once you have the token:"
echo "=========================================="
echo ""
echo "export SUPABASE_ACCESS_TOKEN=\"your-token-here\""
echo ""
echo "Then run your test script:"
echo "./scripts/test-task-execution-prod.sh --scenario simple --repo-url <url>"
echo ""

