/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ReposRepoIdRouteImport } from './routes/repos.$repoId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiTaskRouteImport } from './routes/api/task'
import { Route as ApiRepoRouteImport } from './routes/api/repo'
import { Route as ApiWebhookGithubRouteImport } from './routes/api/webhook.github'
import { Route as ApiWebhookDaytonaRouteImport } from './routes/api/webhook.daytona'
import { Route as ApiWebhookCoderabbitRouteImport } from './routes/api/webhook.coderabbit'
import { Route as ApiTaskTaskIdRouteImport } from './routes/api/task.$taskId'
import { Route as ApiRepoGitingestCallbackRouteImport } from './routes/api/repo.gitingest-callback'
import { Route as ApiRepoConnectRouteImport } from './routes/api/repo.connect'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthMagicLinkRouteImport } from './routes/api/auth/magic-link'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ReposRepoIdTasksNewRouteImport } from './routes/repos.$repoId.tasks.new'
import { Route as ApiTaskTaskIdLogsRouteImport } from './routes/api/task.$taskId.logs'
import { Route as ApiTaskTaskIdExecuteRouteImport } from './routes/api/task.$taskId.execute'
import { Route as ApiTaskTaskIdCancelRouteImport } from './routes/api/task.$taskId.cancel'
import { Route as ApiTaskTaskIdApproveRouteImport } from './routes/api/task.$taskId.approve'
import { Route as ApiRepoRepoIdGitingestReportRouteImport } from './routes/api/repo.$repoId.gitingest-report'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const ReposRepoIdRoute = ReposRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => ReposRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskRoute = ApiTaskRouteImport.update({
  id: '/api/task',
  path: '/api/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepoRoute = ApiRepoRouteImport.update({
  id: '/api/repo',
  path: '/api/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookGithubRoute = ApiWebhookGithubRouteImport.update({
  id: '/api/webhook/github',
  path: '/api/webhook/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookDaytonaRoute = ApiWebhookDaytonaRouteImport.update({
  id: '/api/webhook/daytona',
  path: '/api/webhook/daytona',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookCoderabbitRoute = ApiWebhookCoderabbitRouteImport.update({
  id: '/api/webhook/coderabbit',
  path: '/api/webhook/coderabbit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTaskTaskIdRoute = ApiTaskTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ApiTaskRoute,
} as any)
const ApiRepoGitingestCallbackRoute =
  ApiRepoGitingestCallbackRouteImport.update({
    id: '/gitingest-callback',
    path: '/gitingest-callback',
    getParentRoute: () => ApiRepoRoute,
  } as any)
const ApiRepoConnectRoute = ApiRepoConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ApiRepoRoute,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMagicLinkRoute = ApiAuthMagicLinkRouteImport.update({
  id: '/api/auth/magic-link',
  path: '/api/auth/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRepoIdTasksNewRoute = ReposRepoIdTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => ReposRepoIdRoute,
} as any)
const ApiTaskTaskIdLogsRoute = ApiTaskTaskIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiTaskTaskIdRoute,
} as any)
const ApiTaskTaskIdExecuteRoute = ApiTaskTaskIdExecuteRouteImport.update({
  id: '/execute',
  path: '/execute',
  getParentRoute: () => ApiTaskTaskIdRoute,
} as any)
const ApiTaskTaskIdCancelRoute = ApiTaskTaskIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiTaskTaskIdRoute,
} as any)
const ApiTaskTaskIdApproveRoute = ApiTaskTaskIdApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => ApiTaskTaskIdRoute,
} as any)
const ApiRepoRepoIdGitingestReportRoute =
  ApiRepoRepoIdGitingestReportRouteImport.update({
    id: '/$repoId/gitingest-report',
    path: '/$repoId/gitingest-report',
    getParentRoute: () => ApiRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/repos': typeof ReposRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/repo': typeof ApiRepoRouteWithChildren
  '/api/task': typeof ApiTaskRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/repo/connect': typeof ApiRepoConnectRoute
  '/api/repo/gitingest-callback': typeof ApiRepoGitingestCallbackRoute
  '/api/task/$taskId': typeof ApiTaskTaskIdRouteWithChildren
  '/api/webhook/coderabbit': typeof ApiWebhookCoderabbitRoute
  '/api/webhook/daytona': typeof ApiWebhookDaytonaRoute
  '/api/webhook/github': typeof ApiWebhookGithubRoute
  '/api/repo/$repoId/gitingest-report': typeof ApiRepoRepoIdGitingestReportRoute
  '/api/task/$taskId/approve': typeof ApiTaskTaskIdApproveRoute
  '/api/task/$taskId/cancel': typeof ApiTaskTaskIdCancelRoute
  '/api/task/$taskId/execute': typeof ApiTaskTaskIdExecuteRoute
  '/api/task/$taskId/logs': typeof ApiTaskTaskIdLogsRoute
  '/repos/$repoId/tasks/new': typeof ReposRepoIdTasksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/repos': typeof ReposRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/repo': typeof ApiRepoRouteWithChildren
  '/api/task': typeof ApiTaskRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/repo/connect': typeof ApiRepoConnectRoute
  '/api/repo/gitingest-callback': typeof ApiRepoGitingestCallbackRoute
  '/api/task/$taskId': typeof ApiTaskTaskIdRouteWithChildren
  '/api/webhook/coderabbit': typeof ApiWebhookCoderabbitRoute
  '/api/webhook/daytona': typeof ApiWebhookDaytonaRoute
  '/api/webhook/github': typeof ApiWebhookGithubRoute
  '/api/repo/$repoId/gitingest-report': typeof ApiRepoRepoIdGitingestReportRoute
  '/api/task/$taskId/approve': typeof ApiTaskTaskIdApproveRoute
  '/api/task/$taskId/cancel': typeof ApiTaskTaskIdCancelRoute
  '/api/task/$taskId/execute': typeof ApiTaskTaskIdExecuteRoute
  '/api/task/$taskId/logs': typeof ApiTaskTaskIdLogsRoute
  '/repos/$repoId/tasks/new': typeof ReposRepoIdTasksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/repos': typeof ReposRouteWithChildren
  '/signup': typeof SignupRoute
  '/tasks': typeof TasksRouteWithChildren
  '/api/repo': typeof ApiRepoRouteWithChildren
  '/api/task': typeof ApiTaskRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/repos/$repoId': typeof ReposRepoIdRouteWithChildren
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/repo/connect': typeof ApiRepoConnectRoute
  '/api/repo/gitingest-callback': typeof ApiRepoGitingestCallbackRoute
  '/api/task/$taskId': typeof ApiTaskTaskIdRouteWithChildren
  '/api/webhook/coderabbit': typeof ApiWebhookCoderabbitRoute
  '/api/webhook/daytona': typeof ApiWebhookDaytonaRoute
  '/api/webhook/github': typeof ApiWebhookGithubRoute
  '/api/repo/$repoId/gitingest-report': typeof ApiRepoRepoIdGitingestReportRoute
  '/api/task/$taskId/approve': typeof ApiTaskTaskIdApproveRoute
  '/api/task/$taskId/cancel': typeof ApiTaskTaskIdCancelRoute
  '/api/task/$taskId/execute': typeof ApiTaskTaskIdExecuteRoute
  '/api/task/$taskId/logs': typeof ApiTaskTaskIdLogsRoute
  '/repos/$repoId/tasks/new': typeof ReposRepoIdTasksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/magic-link'
    | '/repos'
    | '/signup'
    | '/tasks'
    | '/api/repo'
    | '/api/task'
    | '/auth/callback'
    | '/repos/$repoId'
    | '/tasks/$taskId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/magic-link'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/repo/connect'
    | '/api/repo/gitingest-callback'
    | '/api/task/$taskId'
    | '/api/webhook/coderabbit'
    | '/api/webhook/daytona'
    | '/api/webhook/github'
    | '/api/repo/$repoId/gitingest-report'
    | '/api/task/$taskId/approve'
    | '/api/task/$taskId/cancel'
    | '/api/task/$taskId/execute'
    | '/api/task/$taskId/logs'
    | '/repos/$repoId/tasks/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/magic-link'
    | '/repos'
    | '/signup'
    | '/tasks'
    | '/api/repo'
    | '/api/task'
    | '/auth/callback'
    | '/repos/$repoId'
    | '/tasks/$taskId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/magic-link'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/repo/connect'
    | '/api/repo/gitingest-callback'
    | '/api/task/$taskId'
    | '/api/webhook/coderabbit'
    | '/api/webhook/daytona'
    | '/api/webhook/github'
    | '/api/repo/$repoId/gitingest-report'
    | '/api/task/$taskId/approve'
    | '/api/task/$taskId/cancel'
    | '/api/task/$taskId/execute'
    | '/api/task/$taskId/logs'
    | '/repos/$repoId/tasks/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/magic-link'
    | '/repos'
    | '/signup'
    | '/tasks'
    | '/api/repo'
    | '/api/task'
    | '/auth/callback'
    | '/repos/$repoId'
    | '/tasks/$taskId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/magic-link'
    | '/api/auth/session'
    | '/api/auth/signup'
    | '/api/repo/connect'
    | '/api/repo/gitingest-callback'
    | '/api/task/$taskId'
    | '/api/webhook/coderabbit'
    | '/api/webhook/daytona'
    | '/api/webhook/github'
    | '/api/repo/$repoId/gitingest-report'
    | '/api/task/$taskId/approve'
    | '/api/task/$taskId/cancel'
    | '/api/task/$taskId/execute'
    | '/api/task/$taskId/logs'
    | '/repos/$repoId/tasks/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  ReposRoute: typeof ReposRouteWithChildren
  SignupRoute: typeof SignupRoute
  TasksRoute: typeof TasksRouteWithChildren
  ApiRepoRoute: typeof ApiRepoRouteWithChildren
  ApiTaskRoute: typeof ApiTaskRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMagicLinkRoute: typeof ApiAuthMagicLinkRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiWebhookCoderabbitRoute: typeof ApiWebhookCoderabbitRoute
  ApiWebhookDaytonaRoute: typeof ApiWebhookDaytonaRoute
  ApiWebhookGithubRoute: typeof ApiWebhookGithubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/repos/$repoId': {
      id: '/repos/$repoId'
      path: '/$repoId'
      fullPath: '/repos/$repoId'
      preLoaderRoute: typeof ReposRepoIdRouteImport
      parentRoute: typeof ReposRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task': {
      id: '/api/task'
      path: '/api/task'
      fullPath: '/api/task'
      preLoaderRoute: typeof ApiTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repo': {
      id: '/api/repo'
      path: '/api/repo'
      fullPath: '/api/repo'
      preLoaderRoute: typeof ApiRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/github': {
      id: '/api/webhook/github'
      path: '/api/webhook/github'
      fullPath: '/api/webhook/github'
      preLoaderRoute: typeof ApiWebhookGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/daytona': {
      id: '/api/webhook/daytona'
      path: '/api/webhook/daytona'
      fullPath: '/api/webhook/daytona'
      preLoaderRoute: typeof ApiWebhookDaytonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/coderabbit': {
      id: '/api/webhook/coderabbit'
      path: '/api/webhook/coderabbit'
      fullPath: '/api/webhook/coderabbit'
      preLoaderRoute: typeof ApiWebhookCoderabbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/task/$taskId': {
      id: '/api/task/$taskId'
      path: '/$taskId'
      fullPath: '/api/task/$taskId'
      preLoaderRoute: typeof ApiTaskTaskIdRouteImport
      parentRoute: typeof ApiTaskRoute
    }
    '/api/repo/gitingest-callback': {
      id: '/api/repo/gitingest-callback'
      path: '/gitingest-callback'
      fullPath: '/api/repo/gitingest-callback'
      preLoaderRoute: typeof ApiRepoGitingestCallbackRouteImport
      parentRoute: typeof ApiRepoRoute
    }
    '/api/repo/connect': {
      id: '/api/repo/connect'
      path: '/connect'
      fullPath: '/api/repo/connect'
      preLoaderRoute: typeof ApiRepoConnectRouteImport
      parentRoute: typeof ApiRepoRoute
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/magic-link': {
      id: '/api/auth/magic-link'
      path: '/api/auth/magic-link'
      fullPath: '/api/auth/magic-link'
      preLoaderRoute: typeof ApiAuthMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$repoId/tasks/new': {
      id: '/repos/$repoId/tasks/new'
      path: '/tasks/new'
      fullPath: '/repos/$repoId/tasks/new'
      preLoaderRoute: typeof ReposRepoIdTasksNewRouteImport
      parentRoute: typeof ReposRepoIdRoute
    }
    '/api/task/$taskId/logs': {
      id: '/api/task/$taskId/logs'
      path: '/logs'
      fullPath: '/api/task/$taskId/logs'
      preLoaderRoute: typeof ApiTaskTaskIdLogsRouteImport
      parentRoute: typeof ApiTaskTaskIdRoute
    }
    '/api/task/$taskId/execute': {
      id: '/api/task/$taskId/execute'
      path: '/execute'
      fullPath: '/api/task/$taskId/execute'
      preLoaderRoute: typeof ApiTaskTaskIdExecuteRouteImport
      parentRoute: typeof ApiTaskTaskIdRoute
    }
    '/api/task/$taskId/cancel': {
      id: '/api/task/$taskId/cancel'
      path: '/cancel'
      fullPath: '/api/task/$taskId/cancel'
      preLoaderRoute: typeof ApiTaskTaskIdCancelRouteImport
      parentRoute: typeof ApiTaskTaskIdRoute
    }
    '/api/task/$taskId/approve': {
      id: '/api/task/$taskId/approve'
      path: '/approve'
      fullPath: '/api/task/$taskId/approve'
      preLoaderRoute: typeof ApiTaskTaskIdApproveRouteImport
      parentRoute: typeof ApiTaskTaskIdRoute
    }
    '/api/repo/$repoId/gitingest-report': {
      id: '/api/repo/$repoId/gitingest-report'
      path: '/$repoId/gitingest-report'
      fullPath: '/api/repo/$repoId/gitingest-report'
      preLoaderRoute: typeof ApiRepoRepoIdGitingestReportRouteImport
      parentRoute: typeof ApiRepoRoute
    }
  }
}

interface ReposRepoIdRouteChildren {
  ReposRepoIdTasksNewRoute: typeof ReposRepoIdTasksNewRoute
}

const ReposRepoIdRouteChildren: ReposRepoIdRouteChildren = {
  ReposRepoIdTasksNewRoute: ReposRepoIdTasksNewRoute,
}

const ReposRepoIdRouteWithChildren = ReposRepoIdRoute._addFileChildren(
  ReposRepoIdRouteChildren,
)

interface ReposRouteChildren {
  ReposRepoIdRoute: typeof ReposRepoIdRouteWithChildren
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposRepoIdRoute: ReposRepoIdRouteWithChildren,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface ApiRepoRouteChildren {
  ApiRepoConnectRoute: typeof ApiRepoConnectRoute
  ApiRepoGitingestCallbackRoute: typeof ApiRepoGitingestCallbackRoute
  ApiRepoRepoIdGitingestReportRoute: typeof ApiRepoRepoIdGitingestReportRoute
}

const ApiRepoRouteChildren: ApiRepoRouteChildren = {
  ApiRepoConnectRoute: ApiRepoConnectRoute,
  ApiRepoGitingestCallbackRoute: ApiRepoGitingestCallbackRoute,
  ApiRepoRepoIdGitingestReportRoute: ApiRepoRepoIdGitingestReportRoute,
}

const ApiRepoRouteWithChildren =
  ApiRepoRoute._addFileChildren(ApiRepoRouteChildren)

interface ApiTaskTaskIdRouteChildren {
  ApiTaskTaskIdApproveRoute: typeof ApiTaskTaskIdApproveRoute
  ApiTaskTaskIdCancelRoute: typeof ApiTaskTaskIdCancelRoute
  ApiTaskTaskIdExecuteRoute: typeof ApiTaskTaskIdExecuteRoute
  ApiTaskTaskIdLogsRoute: typeof ApiTaskTaskIdLogsRoute
}

const ApiTaskTaskIdRouteChildren: ApiTaskTaskIdRouteChildren = {
  ApiTaskTaskIdApproveRoute: ApiTaskTaskIdApproveRoute,
  ApiTaskTaskIdCancelRoute: ApiTaskTaskIdCancelRoute,
  ApiTaskTaskIdExecuteRoute: ApiTaskTaskIdExecuteRoute,
  ApiTaskTaskIdLogsRoute: ApiTaskTaskIdLogsRoute,
}

const ApiTaskTaskIdRouteWithChildren = ApiTaskTaskIdRoute._addFileChildren(
  ApiTaskTaskIdRouteChildren,
)

interface ApiTaskRouteChildren {
  ApiTaskTaskIdRoute: typeof ApiTaskTaskIdRouteWithChildren
}

const ApiTaskRouteChildren: ApiTaskRouteChildren = {
  ApiTaskTaskIdRoute: ApiTaskTaskIdRouteWithChildren,
}

const ApiTaskRouteWithChildren =
  ApiTaskRoute._addFileChildren(ApiTaskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  ReposRoute: ReposRouteWithChildren,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRouteWithChildren,
  ApiRepoRoute: ApiRepoRouteWithChildren,
  ApiTaskRoute: ApiTaskRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMagicLinkRoute: ApiAuthMagicLinkRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiWebhookCoderabbitRoute: ApiWebhookCoderabbitRoute,
  ApiWebhookDaytonaRoute: ApiWebhookDaytonaRoute,
  ApiWebhookGithubRoute: ApiWebhookGithubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
